### ISSUE TITLE
Fintune problem

### ISSUE THREAD

**Issue by cyZhu98** [thuiar/Cross-Modal-BERT#3]
非常感谢作者开源。我注意到你们的代码没有解冻最后一层分类层，我加上对比了下，精度稍微低了一点，不过这有可能是因为超参不合适。你们这样做是因为解冻分类层效果会更差，还是说有其他什么讲究呢？
i wonder why you didn't unfreeze the classifier layer in run_classifier.py line129 ?
I got a slightly lower accuracy when i unfreezed 'classifier' which may due to the unmatched hyperparameters, or is there something else

**Comment by kaichengyang0828** [comment]
您好，感谢您的关注。事实上并没有什么讲究，您可以不用过于纠结，他们效果应该是差不多的，您可以多尝试下其他超参数。

**Comment by cyZhu98** [comment]
好的，谢谢！
