### ISSUE TITLE
没有处理视频数据的代码，数据只是传了进去，但是没有进行处理？？？

### ISSUE THREAD

**Issue by zhaohongwei1998** [thuiar/Cross-Modal-BERT#4]
![image](https://user-images.githubusercontent.com/70933342/141876058-357c8999-1756-46e4-9889-65e585e6a2d1.png)
是出于保密的原因吗？

**Comment by kaichengyang0828** [comment]
很抱歉给你带来了困扰，在该function中并没有使用audio_data，因为这里是用BERT来学习text对应的feature vector，audio_data真正发挥作用是在BertFinetun()中

**Comment by zhaohongwei1998** [comment]
看到了，谢谢你我有个疑问，为什么你不用huggingface，却自己写bert啊
最近也在看M-BERT这篇文章，和您的文章有很多类似的点，他是改的hugging_face中的BERT_Model类
https://github.com/WasifurRahman/BERT_multimodal_transformer






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaicheng ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 中午1:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuiar/Cross-Modal-BERT] 没有处理视频数据的代码，数据只是传了进去，但是没有进行处理？？？ (Issue #4)





 
很抱歉给你带来了困扰，在该function中并没有使用audio_data，因为这里是用BERT来学习text对应的feature vector，audio_data真正发挥作用是在BertFinetun()中
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaichengyang0828** [comment]
Hi,事实上BERT部分的代码就是使用的huggingface的代码，只不过是很早之前的版本(大约是19年左右的版本)，当时BERT刚兴起用过几次，就直接拿来用了，没有用目前最新版本的代码。

**Comment by zhaohongwei1998** [comment]
我是看着有点像，哈哈哈，因为你都写在一个文件里了，误以为不是huggingface你最近还在搞多模态情感分析方向吗
我目前研究方向也是这个，方便的话可以和大佬多交流交流
我在天津科技大学的，目前研二




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaicheng ***@***.***&gt;; 
发送时间: 2021年11月17日(星期三) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuiar/Cross-Modal-BERT] 没有处理视频数据的代码，数据只是传了进去，但是没有进行处理？？？ (Issue #4)





 
Hi,事实上BERT部分的代码就是使用的huggingface的代码，只不过是很早之前的版本(大约是19年左右的版本)，当时BERT刚兴起用过几次，就直接拿来用了，没有用目前最新版本的代码。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaichengyang0828** [comment]
已经是社畜了，毕业一年了，我们组还有师弟继续研究这个方向，有兴趣可以多关注一下实验室主页https://thuiar.github.io/

**Comment by zhaohongwei1998** [comment]
好嘞，谢谢你，方便的话可以加你个微信吗，我微信号：zhwdiy1



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kaicheng ***@***.***&gt;; 
发送时间: 2021年11月17日(星期三) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuiar/Cross-Modal-BERT] 没有处理视频数据的代码，数据只是传了进去，但是没有进行处理？？？ (Issue #4)





 
已经是社畜了，毕业一年了，我们组还有师弟继续研究这个方向，有兴趣可以多关注一下实验室主页https://thuiar.github.io/
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
